version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/docker
    build:
      context: pipeline    
    ports:
      - "8080:8080"
    volumes:
      #- $PWD/jenkins_home:/var/jenkins_home
      - /var/docker/jenkis-trainning/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: centos7
    volumes:
      - $PWD/aws-s3.sh:/tmp/script.sh
      - /var/run/docker.sock:/var/run/docker.sock
      #- $PWD/registry:/tmp/registry
      - /var/docker/jenkis-trainning/registry:/tmp/registry
    networks:
      - net
  db_host:
    container_name: db
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      #- $PWD/db_data:/var/lib/mysql
      - /var/docker/jenkis-trainning/db_data:/var/lib/mysql
    networks:
      - net
  web:
    container_name: web
    image: ansible-web
    build:
      context: jenkins-ansible/web
    ports:
      - "8888:80"
    networks:
      - net
  git:
    container_name: git-server
    hostname: gitlab.example.com
    ports:
      - "443:443"
      - "80:80"
    volumes:
      #- "$PWD/gitlab/config:/etc/gitlab"
      #- "$PWD/gitlab/logs:/var/log/gitlab"
      #- "$PWD/gitlab/data:/var/opt/gitlab"
      - "/var/docker/jenkis-trainning/gitlab/config:/etc/gitlab"
      - "/var/docker/jenkis-trainning/gitlab/logs:/var/log/gitlab"
      - "/var/docker/jenkis-trainning/gitlab/data:/var/opt/gitlab"         
    image: gitlab/gitlab-ce
    networks:
      - net
networks:
  net:
